export const MarketInterventionLedgerAbi = [
  {
    type: "constructor",
    payable: false,
    inputs: [{ type: "address", name: "_mainTokenAddress" }],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeAssetManagerAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isAssetManager", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeEcosystemAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isEcosystem", indexed: false },
    ],
  },
  {
    type: "function",
    name: "_changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "_changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addIntervention",
    constant: false,
    payable: false,
    inputs: [
      { type: "bool", name: "isBuyback" },
      { type: "uint256", name: "_numberOfTokens" },
      { type: "uint256", name: "_valueInETH" },
      { type: "uint256", name: "_valueInUSDC" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getInterventionByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { type: "uint256", name: "interventionID" },
          { type: "uint256", name: "timeStamp" },
          { type: "bool", name: "buyback" },
          { type: "uint256", name: "numberOfTokens" },
          { type: "uint256", name: "valueInETH" },
          { type: "uint256", name: "valueInUSDC" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getInterventionIsBuybackByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "getInterventionNumberOFTokensByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getInterventionTimeStampByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getInterventionValueInETHByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getInterventionValueInUSDCByID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "_interventionID" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getLastInterventionID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getLastInterventionTimeStamp",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getUnlockTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isAssetManager",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isEcosystem",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "lock",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "time" }],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setAddressesAndEcosystem",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_mainTokenAddress" },
      { type: "address", name: "_dividendTrackerAddress" },
      { type: "address", name: "_priceFetcherAddress" },
      { type: "address", name: "_treasuryContractAddress" },
      { type: "address", name: "_taxManagerAddress" },
      { type: "address", name: "_bondDepositoryAddress" },
      { type: "address", name: "_secondServiceContractAddress" },
      { type: "address", name: "_thirdServiceContractAddress" },
      { type: "address", name: "_marketInterventionLedgerAddress" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unlock",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateBondDepoWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newBondDepoWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateBondDepositoryAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newBondDepositoryAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateDividendTrackerAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newDividendTrackerAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateLiquidityWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newLiquidityWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateMainContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newMainTokenAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateMarketInterventionLedger",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newMarketInterventionLedgerAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateMarketingWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newMarketingWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePriceFetcherAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newPriceFetcherAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateSecondServiceContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newSecondServiceContractAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateSecondServiceWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newSecondServiceWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTaxManagerAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTaxManagerAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateThirdServiceWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newThirdServiceWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTreasuryContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTreasuryContractAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTreasuryWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTreasuryWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUSDCAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUSDCAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapFactoryAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapFactoryAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapPairAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapPairAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapRouterAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapRouterAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateWETHAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newWETHAddress" }],
    outputs: [],
  },
];
