export const TestCapTreasuryAbi = [
  {
    type: "constructor",
    payable: false,
    inputs: [
      { type: "address", name: "_mainTokenAddress" },
      { type: "address", name: "_uniswapRouterAddress" },
      { type: "address", name: "_USDCAddress" },
      { type: "address", name: "_treasuryWalletAddress" },
      { type: "address", name: "_marketingWalletAddress" },
      { type: "address", name: "_liquidityWalletAddress" },
      { type: "address", name: "_bondDepoWalletAddress" },
      { type: "address", name: "_secondServiceWalletAddress" },
      { type: "address", name: "_thirdServiceWalletAddress" },
      { type: "address", name: "_priceFetcherAddress" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SwapETHForTokens",
    inputs: [
      { type: "uint256", name: "amountIn", indexed: false },
      { type: "uint256", name: "tokenAmountReceived", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SwapTokensForETH",
    inputs: [
      { type: "uint256", name: "amountIn", indexed: false },
      { type: "uint256", name: "ETHAmountReceived", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "addAssetEvent",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "string", name: "funName", indexed: false },
      { type: "uint256", name: "assetId", indexed: false },
      { type: "address", name: "_assetAddr", indexed: false },
      { type: "string", name: "_assetName", indexed: false },
      { type: "uint256", name: "_quantity", indexed: false },
      { type: "uint256", name: "_priceInWETH", indexed: false },
      { type: "uint256", name: "_priceInUSDC", indexed: false },
      { type: "uint256", name: "_valueInWETH", indexed: false },
      { type: "uint256", name: "_valueInUSDC", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "buybackEvent",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "topZoneBorder", indexed: false },
      { type: "uint256", name: "estPriceAfterSwap", indexed: false },
      { type: "uint256", name: "lpTestCapReserves", indexed: false },
      { type: "uint256", name: "lpWETHReserves", indexed: false },
      { type: "uint256", name: "_targetPrice", indexed: false },
      { type: "uint256", name: "WETHPriceInUSDC", indexed: false },
      { type: "uint256", name: "_targetPriceWETH", indexed: false },
      { type: "uint256", name: "_targetWETHReserve", indexed: false },
      { type: "uint256", name: "_amountETH", indexed: false },
      { type: "string", name: "caught_error", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeAssetManagerAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isAssetManager", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeEcosystemAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isEcosystem", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "sellbackEvent",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "bottomZoneBorder", indexed: false },
      { type: "uint256", name: "estPriceAfterSwap", indexed: false },
      { type: "uint256", name: "lpTestCapReserves", indexed: false },
      { type: "uint256", name: "lpWETHReserves", indexed: false },
      { type: "uint256", name: "_targetPrice", indexed: false },
      { type: "uint256", name: "WETHPriceInUSDC", indexed: false },
      { type: "uint256", name: "_targetPriceWETH", indexed: false },
      { type: "uint256", name: "_targetTokenReserve", indexed: false },
      { type: "uint256", name: "_amountToSell", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "updateAssetEvent",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "string", name: "funName", indexed: false },
      { type: "uint256", name: "assetId", indexed: false },
      { type: "address", name: "_assetAddr", indexed: false },
      { type: "string", name: "_assetName", indexed: false },
      { type: "uint256", name: "_quantity", indexed: false },
      { type: "uint256", name: "_priceInWETH", indexed: false },
      { type: "uint256", name: "_priceInUSDC", indexed: false },
    ],
  },
  {
    type: "function",
    name: "_changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "_changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addAutoAsset",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_assetAddr" },
      { type: "string", name: "_assetName" },
      { type: "uint256", name: "_chainId" },
      { type: "string", name: "_chainName" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addManualAsset",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_assetAddr" },
      { type: "string", name: "_assetName" },
      { type: "uint256", name: "_chainId" },
      { type: "string", name: "_chainName" },
      { type: "uint256", name: "_quantity" },
      { type: "uint256", name: "_priceInWETH" },
      { type: "uint256", name: "_priceInUSDC" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "currentTreasuryValue",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getLastIndexNumber",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getNumberOfTreasuryAssets",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetAddressById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetByAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_assetAddr" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { type: "uint256", name: "assetId" },
          { type: "address", name: "assetAddress" },
          { type: "string", name: "assetName" },
          { type: "uint256", name: "chainId" },
          { type: "string", name: "chainName" },
          { type: "uint256", name: "quantity" },
          { type: "uint256", name: "priceInWETH" },
          { type: "uint256", name: "priceInUSDC" },
          { type: "uint256", name: "valueInWETH" },
          { type: "uint256", name: "valueInUSDC" },
          { type: "bool", name: "manual" },
          { type: "bool", name: "included" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getTreasuryAssetById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { type: "uint256", name: "assetId" },
          { type: "address", name: "assetAddress" },
          { type: "string", name: "assetName" },
          { type: "uint256", name: "chainId" },
          { type: "string", name: "chainName" },
          { type: "uint256", name: "quantity" },
          { type: "uint256", name: "priceInWETH" },
          { type: "uint256", name: "priceInUSDC" },
          { type: "uint256", name: "valueInWETH" },
          { type: "uint256", name: "valueInUSDC" },
          { type: "bool", name: "manual" },
          { type: "bool", name: "included" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getTreasuryAssetChainIdById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetChainNameById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetIsIncludedById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetIsManualById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetNameById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetPriceInUSDCById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetPriceInWETHById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetQuantityById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetValueInUSDCById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryAssetValueInWETHById",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "assetId" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryContractETHBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTreasuryETHBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getUnlockTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getUpdatedTreasuryValue",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "includeAssetByAddress",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_assetAddr" },
      { type: "bool", name: "_include" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "includeAssetByID",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "id" },
      { type: "bool", name: "_include" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "includeAutoOrManualAssets",
    constant: false,
    payable: false,
    inputs: [
      { type: "bool", name: "_manual" },
      { type: "bool", name: "_include" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isAssetIncluded",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_asset" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isAssetManager",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isEcosystem",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "lastAssetIndex",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lock",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "time" }],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setAddressesAndEcosystem",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_mainTokenAddress" },
      { type: "address", name: "_dividendTrackerAddress" },
      { type: "address", name: "_priceFetcherAddress" },
      { type: "address", name: "_treasuryContractAddress" },
      { type: "address", name: "_taxManagerAddress" },
      { type: "address", name: "_bondDepositoryAddress" },
      { type: "address", name: "_secondServiceContractAddress" },
      { type: "address", name: "_thirdServiceContractAddress" },
      { type: "address", name: "_metricsTrackerAddress" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setManualTreasuryValue",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_manualTreasuryValue" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTryCatchSwitch",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "switchOn" }],
    outputs: [],
  },
  {
    type: "function",
    name: "swapETHForTokens",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "amount" }],
    outputs: [],
  },
  {
    type: "function",
    name: "swapTokensForETH",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "tokenAmount" }],
    outputs: [],
  },
  {
    type: "function",
    name: "switchUpdateModeByAddress",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_assetAddr" },
      { type: "bool", name: "_manual" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "switchUpdateModeByID",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "id" },
      { type: "bool", name: "_manual" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unlock",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAutoAssetByID",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "id" },
      { type: "address", name: "_assetAddr" },
      { type: "string", name: "_assetName" },
      { type: "uint256", name: "_chainId" },
      { type: "string", name: "_chainName" },
      { type: "bool", name: "_manualUpdate" },
      { type: "bool", name: "_include" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAutoAssetPriceByAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_assetAddr" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateAutoAssetPriceByID",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "id" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateBondDepoWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newBondDepoWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateBondDepositoryAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newBondDepositoryAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateDividendTrackerAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newDividendTrackerAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateLiquidityWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newLiquidityWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateMainContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newMainTokenAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateManualAssetByID",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "id" },
      { type: "address", name: "_assetAddr" },
      { type: "string", name: "_assetName" },
      { type: "uint256", name: "_chainId" },
      { type: "string", name: "_chainName" },
      { type: "uint256", name: "_quantity" },
      { type: "uint256", name: "_priceInWETH" },
      { type: "uint256", name: "_priceInUSDC" },
      { type: "bool", name: "_manualUpdate" },
      { type: "bool", name: "_include" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateManualAssetPriceAndQuantityByAddress",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_assetAddr" },
      { type: "uint256", name: "_quantity" },
      { type: "uint256", name: "_priceInWETH" },
      { type: "uint256", name: "_priceInUSDC" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateManualAssetPriceAndQuantityByID",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "id" },
      { type: "uint256", name: "_quantity" },
      { type: "uint256", name: "_priceInWETH" },
      { type: "uint256", name: "_priceInUSDC" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateMarketingWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newMarketingWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePriceFetcherAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newPriceFetcherAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateSecondServiceContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newSecondServiceContractAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateSecondServiceWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newSecondServiceWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTaxManagerAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTaxManagerAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateThirdServiceWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newThirdServiceWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTreasuryContractAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTreasuryContractAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTreasuryTokenValueandQuantity",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateTreasuryWalletAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newTreasuryWalletAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUSDCAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUSDCAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapFactoryAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapFactoryAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapPairAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapPairAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateUniswapRouterAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newUniswapRouterAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateWETHAddress",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newWETHAddress" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updatemetricsTracker",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_newmetricsTrackerAddress" }],
    outputs: [],
  },
];
