export const TestCapitalAbi = [
  {
    type: "constructor",
    payable: false,
    inputs: [
      { type: "address", name: "_uniswapRouterAddress" },
      { type: "address", name: "_USDCAddress" },
      { type: "address", name: "_treasuryWalletAddress" },
      { type: "address", name: "_marketingWalletAddress" },
      { type: "address", name: "_liquidityWalletAddress" },
      { type: "address", name: "_bondDepoWalletAddress" },
      { type: "address", name: "_secondServiceWalletAddress" },
      { type: "address", name: "_thirdServiceWalletAddress" },
      { type: "address[]", name: "whitelistAddress" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "AdressLog",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "address", name: "sender", indexed: false },
      { type: "address", name: "recepient", indexed: false },
      { type: "address", name: "thisAddr", indexed: false },
      { type: "address", name: "pair", indexed: false },
      { type: "address", name: "router", indexed: false },
      { type: "address", name: "factory", indexed: false },
      { type: "address", name: "dividendTracker", indexed: false },
      { type: "uint256", name: "amount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Approval",
    inputs: [
      { type: "address", name: "owner", indexed: true },
      { type: "address", name: "spender", indexed: true },
      { type: "uint256", name: "value", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "BuyBack",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "currentPriceInWETH", indexed: false },
      { type: "uint256", name: "targetPriceInWETH", indexed: false },
      { type: "uint256", name: "targetWETHInLP", indexed: false },
      { type: "uint256", name: "currentWETHInLP", indexed: false },
      { type: "uint256", name: "amountETHForPurchase", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "DividendSell",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "amountTokensForSell", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "DividendSwap",
    inputs: [
      { type: "uint256", name: "tokensSwapped", indexed: false },
      { type: "uint256", name: "ethReceived", indexed: false },
      { type: "uint256", name: "tokensIntoLiqudity", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "DividendSwapEnabledUpdated",
    inputs: [{ type: "bool", name: "enabled", indexed: false }],
  },
  {
    type: "event",
    anonymous: false,
    name: "ETHSentFromMainContract",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "amountETHSent", indexed: false },
      { type: "address", name: "addressSentTo", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SellBack",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "uint256", name: "currentPriceInWETH", indexed: false },
      { type: "uint256", name: "targetPriceInWETH", indexed: false },
      { type: "uint256", name: "targetBoomInLP", indexed: false },
      {
        type: "uint256",
        name: "currentBoomTokensInLP",
        indexed: false,
      },
      { type: "uint256", name: "amountTokensForSell", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SendDividends",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      {
        type: "address",
        name: "dividendTrackerAddress",
        indexed: false,
      },
      { type: "uint256", name: "tokensSwapped", indexed: false },
      { type: "uint256", name: "amount", indexed: false },
      { type: "bool", name: "success", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SwapETHForTokens",
    inputs: [
      { type: "uint256", name: "amountIn", indexed: false },
      { type: "uint256", name: "tokenAmountReceived", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "SwapTokensForETH",
    inputs: [
      { type: "uint256", name: "amountIn", indexed: false },
      { type: "uint256", name: "ETHAmountReceived", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Transfer",
    inputs: [
      { type: "address", name: "from", indexed: true },
      { type: "address", name: "to", indexed: true },
      { type: "uint256", name: "value", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "_transferFunctionCalled",
    inputs: [
      { type: "address", name: "msgSender", indexed: false },
      { type: "address", name: "sender", indexed: false },
      { type: "address", name: "recipient", indexed: false },
      { type: "uint256", name: "amount", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeAssetManagerAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isAssetManager", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "changeEcosystemAddress",
    inputs: [
      { type: "address", name: "_addr", indexed: true },
      { type: "bool", name: "_isEcosystem", indexed: false },
    ],
  },
  {
    type: "function",
    name: "DEAD",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "Sweep",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "USDCAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "WETHAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "ZERO",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "_changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "_changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "_sellHistories",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256" }],
    outputs: [
      { type: "uint256", name: "time" },
      { type: "uint256", name: "tokenAmount" },
    ],
  },
  {
    type: "function",
    name: "allowance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "owner" },
      { type: "address", name: "spender" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "spender" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoBackingUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoBuyBacks",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoInterventionLimitsUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoSellBacks",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoTaxUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoTreasuryValueUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "autoZoneUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "bondDepoWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "buyBackTimeInterval",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "buybackETHMinimum",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "changeAssetManagerList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "changeEcosystemList",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "bool", name: "_access" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "circulatingSupply",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "currentPriceUpdates",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "decimals",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "decreaseAllowance",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "spender" },
      { type: "uint256", name: "subtractedValue" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "dividendSwapEnabled",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "dynamicOperatingModel",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "excludeFromFee",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "account" },
      { type: "bool", name: "isExcluded" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "excludeFromMaxTx",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "account" },
      { type: "bool", name: "isExcluded" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "excludeFromMaxWallet",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "account" },
      { type: "bool", name: "isExcluded" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "excludeFromTaxWalletAndTxLimits",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "excludedAddr" },
      { type: "bool", name: "_exclude" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "geEstWETHInLPAfterSwap",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getBackingPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentBoomTokensInLP",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentDividendFeeShareBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentLiquidityFeeShareBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentTreasuryFeeShareBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentWETHInLP",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentZone",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentZoneBottomPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getCurrentZoneTopPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getEstBoomTokensInLPAfterSwap",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getEstPriceAfterSwap",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getFairPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getMarketingFeeShareBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTotalBuyFeeBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getTotalSellFeeBPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getUnlockTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "increaseAllowance",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "spender" },
      { type: "uint256", name: "addedValue" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "intervalMinutesForSwap",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isAssetManager",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isEcosystem",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isExcludedFromFee",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isExcludedFromMaxTx",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isExcludedFromMaxWallet",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "account" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isOpen",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "lastBuyBackTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lastSellBackTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "lastSwapTime",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "launchIgnitionPhase",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "liquidityWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "lock",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "time" }],
    outputs: [],
  },
  {
    type: "function",
    name: "marketingWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "minimumTokensBeforeSwapAmount",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "ownerApprovalChange",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "tokenOwner" },
      { type: "address", name: "spender" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pullOpModelFromTaxManager",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "secondServiceWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "sellBackTimeInterval",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "sellbackTokenMinimum",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "setAddressesAndEcosystem",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_dividendTrackerAddress" },
      { type: "address", name: "_priceFetcherAddress" },
      { type: "address", name: "_treasuryContractAddress" },
      { type: "address", name: "_taxManagerAddress" },
      { type: "address", name: "_bondDepositoryAddress" },
      { type: "address", name: "_secondServiceContractAddress" },
      { type: "address", name: "_thirdServiceContractAddress" },
      { type: "address", name: "_metricsTrackerAddress" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setCurrentPriceUpdates",
    constant: false,
    payable: false,
    inputs: [{ type: "bool", name: "_currentPriceUpdates" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setEcosystemExclusions",
    constant: false,
    payable: false,
    inputs: [{ type: "bool", name: "_exclude" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFlagsForOpModel",
    constant: false,
    payable: false,
    inputs: [
      { type: "bool", name: "_dynamicOperatingModel" },
      { type: "bool", name: "_autoTaxUpdates" },
      { type: "bool", name: "_autoZoneUpdates" },
      { type: "bool", name: "_autoBackingUpdates" },
      { type: "bool", name: "_autoInterventionLimitsUpdates" },
      { type: "bool", name: "_autoTreasuryValueUpdates" },
      { type: "bool", name: "_autoBuyBacks" },
      { type: "bool", name: "_autoSellBacks" },
      { type: "bool", name: "_dividendSwapEnabled" },
      { type: "bool", name: "_taxEnabled" },
      { type: "bool", name: "_swapAllToken" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setLimitsAndThresholdsForOpModel",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "_minimumTokensBeforeSwap" },
      { type: "uint256", name: "_maxTxBPS" },
      { type: "uint256", name: "_maxWalletBPS" },
      { type: "uint256", name: "_buybackETHMinimum" },
      { type: "uint256", name: "_sellbackTokenMinimum" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setTotalBuyFeeBPS",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_newTotalBuyFeeBPS" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTotalSellFeeBPS",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "_newTotalSellFeeBPS" }],
    outputs: [],
  },
  {
    type: "function",
    name: "swapAllTokens",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "symbol",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "taxEnabled",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "thirdServiceWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "totalSupply",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "transfer",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "recipient" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "transferForeignToken",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "_token" },
      { type: "address", name: "_to" },
    ],
    outputs: [{ type: "bool", name: "_sent" }],
  },
  {
    type: "function",
    name: "transferFrom",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "sender" },
      { type: "address", name: "recipient" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "treasuryWalletAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "uniswapV2Router",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "unlock",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateCirculatingSupply",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
];
